IntegrateApplicationInsights/WebApp/Controllers/HomeController.cs
using Microsoft.ApplicationInsights;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var MyMetrics = new Dictionary<string, double>
            {
                { "Measure 1", DateTime.UtcNow.Hour },
                { "Measure 2", DateTime.UtcNow.Second }
            };
            new TelemetryClient().TrackEvent(nameof(Index), null, MyMetrics);

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Integrate Application Insights";

            var MyMetrics = new Dictionary<string, double>
            {
                { "Measure 1", DateTime.UtcNow.Minute },
                { "Measure 2", DateTime.UtcNow.Second }
            };
            new TelemetryClient().TrackEvent(nameof(About), null, MyMetrics);

            return View();
        }

        public ActionResult Contact()
        {
            var MyMetrics = new Dictionary<string, double>
            {
                { "Measure 1", DateTime.UtcNow.Hour },
                { "Measure 2", DateTime.UtcNow.Second }
            };
            new TelemetryClient().TrackEvent(nameof(Contact), null, MyMetrics);

            ViewBag.Message = "Integrate Application Insights";

            return View();
        }
    }
}

IntegrateApplicationInsights/WebApp/Controllers/MyGreatTableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
	public class MyGreatTableController : Controller
	{
		// GET: MyGreatTable
		public ActionResult Index()
		{
			using (MyDbContext context = new MyDbContext())
			{
				return View(context.MyGreatTables.ToList());
			}
		}

		// GET: MyGreatTable/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: MyGreatTable/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: MyGreatTable/Create
		[HttpPost]
		[ValidateAntiForgeryToken()]
		public ActionResult Create(MyGreatTable model)
		{
			if (ModelState.IsValid)
				try
				{
					using (MyDbContext context = new MyDbContext())
					{
						context.MyGreatTables.Add(model);
						context.SaveChanges();
					}

					return RedirectToAction("Index");
				}
				catch
				{
					return View();
				}
			else
				return View(model);
		}

		// GET: MyGreatTable/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: MyGreatTable/Edit/5
		[HttpPost]
		public ActionResult Edit(int id, MyGreatTable model)
		{
			try
			{
				// TODO: Add edit logic here

				return RedirectToAction("Index");
			}
			catch
			{
				return View(model);
			}
		}

		// GET: MyGreatTable/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: MyGreatTable/Delete/5
		[HttpPost]
		public ActionResult Delete(int id, FormCollection collection)
		{
			try
			{
				// TODO: Add delete logic here

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}
	}
}

IntegrateApplicationInsights/WebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<p>Sample app for a talk by Sven Aelterman.</p>

IntegrateApplicationInsights/WebApp/Views/Home/Contact.cshtml
@{
	ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<address>
	327 Bibb Graves Hall<br />
	Troy University<br />
	Troy, AL 36082<br />
	<abbr title="Phone">P:</abbr>
	334-670-3922
</address>

<address>
	<strong>Support:</strong>   <a href="mailto:nohelp@getlost.com">nohelp@getlost.com</a><br />
	<strong>Marketing:</strong> <a href="mailto:payhere@forservice.com">payhere@forservice.com</a>
</address>

IntegrateApplicationInsights/WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Integrate Application Insights</h1>
    <p class="lead">Look at this great data!</p>
    <p><a href="@Url.Action("Index", "MyGreatTable")" class="btn btn-primary btn-lg">See it&nbsp;&raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>